/*******************************************************************************
 * Copyright (c) 2011 Lab-STICC Universite de Bretagne Sud, Lorient.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the CeCILL-B license available
 * at :
 * en : http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
 * fr : http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.html
 * 
 * Contributors:
 * Dominique BLOUIN (Lab-STICC UBS), dominique.blouin@univ-ubs.fr
 ******************************************************************************/
/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.labsticc.framework.settings.model.settings.provider;

import fr.labsticc.framework.settings.model.settings.util.SettingsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SettingsItemProviderAdapterFactory extends SettingsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SettingsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.ModelingLanguageAssociations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelingLanguageAssociationsItemProvider modelingLanguageAssociationsItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.ModelingLanguageAssociations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelingLanguageAssociationsAdapter() {
		if (modelingLanguageAssociationsItemProvider == null) {
			modelingLanguageAssociationsItemProvider = new ModelingLanguageAssociationsItemProvider(this);
		}

		return modelingLanguageAssociationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.SettingsSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SettingsSpecificationItemProvider settingsSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.SettingsSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSettingsSpecificationAdapter() {
		if (settingsSpecificationItemProvider == null) {
			settingsSpecificationItemProvider = new SettingsSpecificationItemProvider(this);
		}

		return settingsSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.PropertyToTypesAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyToTypesAssociationItemProvider propertyToTypesAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.PropertyToTypesAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyToTypesAssociationAdapter() {
		if (propertyToTypesAssociationItemProvider == null) {
			propertyToTypesAssociationItemProvider = new PropertyToTypesAssociationItemProvider(this);
		}

		return propertyToTypesAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.ModelingLanguage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelingLanguageItemProvider modelingLanguageItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.ModelingLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelingLanguageAdapter() {
		if (modelingLanguageItemProvider == null) {
			modelingLanguageItemProvider = new ModelingLanguageItemProvider(this);
		}

		return modelingLanguageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.Category} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoryItemProvider categoryItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.Category}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoryAdapter() {
		if (categoryItemProvider == null) {
			categoryItemProvider = new CategoryItemProvider(this);
		}

		return categoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.PropertyToCategoriesAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyToCategoriesAssociationItemProvider propertyToCategoriesAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.PropertyToCategoriesAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyToCategoriesAssociationAdapter() {
		if (propertyToCategoriesAssociationItemProvider == null) {
			propertyToCategoriesAssociationItemProvider = new PropertyToCategoriesAssociationItemProvider(this);
		}

		return propertyToCategoriesAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.settings.model.settings.ServiceDescriptor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceDescriptorItemProvider serviceDescriptorItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.settings.model.settings.ServiceDescriptor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceDescriptorAdapter() {
		if (serviceDescriptorItemProvider == null) {
			serviceDescriptorItemProvider = new ServiceDescriptorItemProvider(this);
		}

		return serviceDescriptorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (modelingLanguageAssociationsItemProvider != null) modelingLanguageAssociationsItemProvider.dispose();
		if (settingsSpecificationItemProvider != null) settingsSpecificationItemProvider.dispose();
		if (propertyToTypesAssociationItemProvider != null) propertyToTypesAssociationItemProvider.dispose();
		if (modelingLanguageItemProvider != null) modelingLanguageItemProvider.dispose();
		if (categoryItemProvider != null) categoryItemProvider.dispose();
		if (propertyToCategoriesAssociationItemProvider != null) propertyToCategoriesAssociationItemProvider.dispose();
		if (serviceDescriptorItemProvider != null) serviceDescriptorItemProvider.dispose();
	}

}
