/*******************************************************************************
 * Copyright (c) 2011 Lab-STICC Universite de Bretagne Sud, Lorient.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the CeCILL-B license available
 * at :
 * en : http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
 * fr : http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.html
 * 
 * Contributors:
 * Dominique BLOUIN (Lab-STICC UBS), dominique.blouin@univ-ubs.fr
 ******************************************************************************/
/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package fr.labsticc.framework.constraints.model.constraints.provider;

import fr.labsticc.framework.constraints.model.constraints.util.ConstraintsAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ConstraintsItemProviderAdapterFactory extends ConstraintsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ConstraintsItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.FormalConstraintLanguage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FormalConstraintLanguageItemProvider formalConstraintLanguageItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.FormalConstraintLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFormalConstraintLanguageAdapter() {
		if (formalConstraintLanguageItemProvider == null) {
			formalConstraintLanguageItemProvider = new FormalConstraintLanguageItemProvider(this);
		}

		return formalConstraintLanguageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.NaturalConstraintLanguage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NaturalConstraintLanguageItemProvider naturalConstraintLanguageItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.NaturalConstraintLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNaturalConstraintLanguageAdapter() {
		if (naturalConstraintLanguageItemProvider == null) {
			naturalConstraintLanguageItemProvider = new NaturalConstraintLanguageItemProvider(this);
		}

		return naturalConstraintLanguageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.ConstraintLanguagesSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintLanguagesSpecificationItemProvider constraintLanguagesSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.ConstraintLanguagesSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintLanguagesSpecificationAdapter() {
		if (constraintLanguagesSpecificationItemProvider == null) {
			constraintLanguagesSpecificationItemProvider = new ConstraintLanguagesSpecificationItemProvider(this);
		}

		return constraintLanguagesSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.FormalLanguageLibrary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FormalLanguageLibraryItemProvider formalLanguageLibraryItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.FormalLanguageLibrary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFormalLanguageLibraryAdapter() {
		if (formalLanguageLibraryItemProvider == null) {
			formalLanguageLibraryItemProvider = new FormalLanguageLibraryItemProvider(this);
		}

		return formalLanguageLibraryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.FormalLanguageExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FormalLanguageExpressionItemProvider formalLanguageExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.FormalLanguageExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFormalLanguageExpressionAdapter() {
		if (formalLanguageExpressionItemProvider == null) {
			formalLanguageExpressionItemProvider = new FormalLanguageExpressionItemProvider(this);
		}

		return formalLanguageExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.NaturalLanguageExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NaturalLanguageExpressionItemProvider naturalLanguageExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.NaturalLanguageExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNaturalLanguageExpressionAdapter() {
		if (naturalLanguageExpressionItemProvider == null) {
			naturalLanguageExpressionItemProvider = new NaturalLanguageExpressionItemProvider(this);
		}

		return naturalLanguageExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link fr.labsticc.framework.constraints.model.constraints.ServiceDescriptor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceDescriptorItemProvider serviceDescriptorItemProvider;

	/**
	 * This creates an adapter for a {@link fr.labsticc.framework.constraints.model.constraints.ServiceDescriptor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceDescriptorAdapter() {
		if (serviceDescriptorItemProvider == null) {
			serviceDescriptorItemProvider = new ServiceDescriptorItemProvider(this);
		}

		return serviceDescriptorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (constraintLanguagesSpecificationItemProvider != null) constraintLanguagesSpecificationItemProvider.dispose();
		if (formalConstraintLanguageItemProvider != null) formalConstraintLanguageItemProvider.dispose();
		if (naturalConstraintLanguageItemProvider != null) naturalConstraintLanguageItemProvider.dispose();
		if (formalLanguageLibraryItemProvider != null) formalLanguageLibraryItemProvider.dispose();
		if (formalLanguageExpressionItemProvider != null) formalLanguageExpressionItemProvider.dispose();
		if (naturalLanguageExpressionItemProvider != null) naturalLanguageExpressionItemProvider.dispose();
		if (serviceDescriptorItemProvider != null) serviceDescriptorItemProvider.dispose();
	}

}
